FROM python:3.13

WORKDIR /build
COPY . .

ENV TZ="Asia/Shanghai"
ENV EK_IN_DOCKER="1"

RUN python -m pip install --no-cache-dir -U pip uv \
    && uv sync --locked \
    && ln -s /build/scripts/docker-entrypoint-dev.sh /entrypoint.sh \
    && chmod +x /entrypoint.sh

WORKDIR /app
RUN touch config.toml

ENTRYPOINT ["/entrypoint.sh"]
